local L = AceLibrary("AceLocale-2.2"):new("EavesDrop")

L:RegisterTranslations("zhCN", function()
    return {
    		--main
        ["DownTip"] = "点击向下滚动。Shift +点击滚动到底部",
        ["UpTip"] = "点击向上滚动。Shift +点击滚动到顶部",
        ["TabTip"] = "左键拖动框架。右键可查看选项.",
        ["StartCombat"] = "+进入战斗+",
        ["EndCombat"] = "-战斗结束-",
        ["StartCombatTooltip"] = "你进入战斗.",
        ["EndCombatTooltip"] = "你退出战斗.",
        ["DeathTooltip"] = "你死了.",
        ["Buff"] = "Buff",
        ["Debuff"] = "Debuff",
        ["Fades"] = "消失",
        ["PlayerLabel"] = "玩家",
        ["TargetLabel"] = "目标",
        ["Normal"] = "普通",
        ["Crit"] = "暴击",
        ["Skill"] = "技能",
        ["Reset"] = "重置",
        ["OutgoingDamage"] = "施加伤害",
        ["OutgoingHeals"] = "施加治疗",
        ["IncomingDamge"] = "承受伤害",
        ["IncomingHeals"] = "承受治疗",
        ["History"] = "显示战斗记录历史",
		["IncombatSummary"] = "进入战斗时间",
        
        --events
        ["Events"] = "切换事件显示",
        ["ECombat"] = "进入/退出战斗",
        ["ECombatD"] = "显示 进入/退出战斗事件",
        ["EPower"] = "增益获得",
        ["EPowerD"] = "显示获得 魔法/能量/怒气/正面效果",
        ["EBuffs"] = "Buffs",
        ["EBuffsD"] = "显示你获得的buff",
        ["EDebuffs"] = "Debuffs",
        ["EDebuffsD"] = "显示你被施加的debuffs",
        ["EFades"] = "消失",
        ["EFadesD"] = "显示消失的buff和debuff",
        ["EExperience"] = "经验值",
        ["EExperienceD"] = "显示你获得的经验值",
        ["EHonor"] = "荣誉值",
        ["EHonorD"] = "显示你获得的荣誉值",
        ["EReputation"] = "声望值",
        ["EReputationD"] = "显示你获得/失去的声望值",
        ["ESkill"] = "技能",
        ["ESkillD"] = "显示你获得的技能",
        ["EPet"] = "宠物",
        ["EPetD"] = "显示宠物事件",
        ["ESpellcolor"] = "法术伤害颜色",
        ["ESpellcolorD"] = "法术伤害的颜色按照其类别 (神圣, 火焰, 等等...).",
        ["EOverhealing"] = "过量治疗",
        ["EOverhealingD"] = "显示你的过量治疗.",
        ["EHealers"] = "治疗者 ID",
        ["EHealersD"] = "显示谁治疗你.",
        
        --colors
        ["Colors"] = "颜色选项",
        ["IColors"] = "承受事件颜色",
        ["IColorsD"] = "改变承受事件的颜色",
        ["ICHits"] = "攻击命中",
        ["ICHitsD"] = "改变攻击命中的颜色",
        ["ICMiss"] = "未命中",
        ["ICMissD"] = "改变所有未命中颜色 (格挡, 躲闪, 等等...)",
        ["ICHeals"] = "治疗",
        ["ICHealsD"] = "改变治疗颜色",
        ["ICSpells"] = "法术",
        ["ICSpellsD"] = "改变法术/技能颜色",
        ["ICGainsD"] = "改变力量获得颜色",
        ["ICBuffsD"] = "改变buff颜色",
        ["ICDebuffsD"] = "改变debuff颜色",
        ["ICPetD"] = "改变宠物事件颜色",
        ["OColors"] = "施加事件颜色",
        ["OColorsD"] = "改变施加事件的颜色",
        ["OCHitsD"] = "改变你的攻击命中的颜色",
        ["OCSpellsD"] = "改变你的法术/技能颜色",
        ["OCHealsD"] = "改变你的治疗颜色",
        ["OCPetD"] = "改变宠物伤害颜色",
        ["MColors"] = "其他颜色",
        ["MColorsD"] = "改变其他颜色",
        ["MCDeath"] = "死亡",
        ["MCDeathD"] = "改变死亡颜色",
        ["MCMisc"] = "其他",
        ["MCMiscD"] = "改变其他事件颜色",
        ["MCExperienceD"] = "改变经验值获取颜色",
        ["MCReputationD"] = "改变声望事件颜色",
        ["MCHonorD"] = "改变荣誉值事件颜色",
        ["MCSkillD"] = "改变技能事件颜色",
        ["MCFrame"] = "颜色框架",
        ["MCFrameD"] = "改变背景颜色和不透明度",
        ["MCBorder"] = "边框颜色",
        ["MCBorderD"] = "改变边框边框的颜色和不透明度",
        ["MCLabel"] = "标签的颜色",
        ["MCLabelD"] = "更改标签的颜色和不透明度",
        
        --frame
        ["Frame"] = "框架",
        ["FNumber"] = "行数",
        ["FNumberD"] = "显示多少行的事件",
        ["FHeight"] = "高度",
        ["FHeightD"] = "每个行的高度",
        ["FWidth"] = "线条宽度",
        ["FWidthD"] = "每个事件线的宽度",
        ["FText"] = "文字大小",
        ["FTextD"] = "事件文本大小",
        ["FFade"] = "消失的时间",
        ["FFadeD"] = "多久事件开始褪色",
        ["FFadeFrame"] = "褪色的框架",
        ["FFadeFrameD"] = "淡出时，没有行动显示。当任何动作发生时，或者在鼠标滚轮上滚动鼠标.",
        
        --misc
        ["Misc"] = "其他",
        ["MButtons"] = "隐藏滚动按钮",
        ["MButtonsD"] = "隐藏滚动按钮.",
        ["MTooltip"] = "在工具提示中显示详细信息",
        ["MTooltipD"] = "在工具提示中显示给定事件的聊天消息.",
        ["MTimestamp"] = "在提示中显示时间戳",
        ["MTimestampD"] = "聊天信息的工具提示显示时间戳",
        ["MFlip"] = "翻转事件双方",
        ["MFlipD"] = "翻转事件双方.",
        ["MPlace"] = "显示图标",
        ["MPlaceD"] = "显示一个图标的法术/技能",
        ["MHFilter"] = "治疗过滤器",
        ["MHFilterD"] = "控制需要在监视中出现的治疗量，过滤掉频繁的图腾类，祝福类，等等",
        ["MMFilter"] = "力量获取过滤器",
        ["MMFilterD"] = "控制需要在监视中出现的增益，过滤掉频繁的增益就像图腾，祝福，等等。",
        ["MLock"] = "锁 框架",
        ["MLockD"] = "锁定框架，因此无法移动。通过点击选项关闭",
        ["MHistory"] = "历史跟踪",
        ["MHistoryD"] = "跟踪传入和传出事件的最高伤害/治疗的历史.",
        ["MReset"] = "重置预设",
        ["MResetD"] = "重置当前配置文件到默认选项.",
        
    }
end)
