local L = AceLibrary("AceLocale-2.2"):new("sRaidFrames")

-------------------------------------------------------------------------------
-- Localization                                                              --
-------------------------------------------------------------------------------

L:RegisterTranslations("enUS", function() return {
	["hidden"] = true,
	["shown"] = true,
	
	["_Aggro notification"] = true,
	["Aggro notification"] = true,
	["Red name on aggro"] = true,
	["Enable/Disable name color change on aggro"] = true,
	["Red status bar"] = true,
	["Enable/Disable statusbar color change on aggro"] = true,
	["Red aura"] = true,
	["Enable/Disable background color change on aggro"] = true,
	
	["_Pure view"] = true,
	["Pure view"] = true,

	["Status bar - class color"] = true,
	["Class colored status bar"] = true,
	["Unit name - class color"] = true,
	["Class colored unit name"] = true,
	["Status bar - black color"] = true,
	["Black colored status bar when friendly unit is targeting you"] = true,
	
	["Purple colored status bar when friendly unit is targeted by you"] = true,
	["Status bar - purple color"] = true,
	
	["Vertical orientation"] = true,
	["Full size statusbar"] = true,
	["_Healing indicators"] = true,
	["Show/Hide incoming heal indicators"] = true,
	["Round"] = true,
	["Square"] = true,
	["None"] = true,
	["Apply best settings"] = true,
	["Load predefined settings for best visual effect"] = true,
	
	["_Load profiles"] = true,
	["Classic - 5 per column"] = true,
	["Classic - 8 per column"] = true,
	["Classic - 10 per column"] = true,
	["Classic - 20 per column"] = true,
	["Grid - Vertical 8 per column"] = true,
	["Grid - Horizontal 8 per row"] = true,
	["Compact - Vertical 8 per column"] = true,
	["Compact - Horizontal 8 per row"] = true,
	
	["_Focus frame"] = true,
	["Use keybinding to add/remove focus units."] = true,
	["Add WSG carrier to focus"] = true;
	["Auto add WSG carrier to focus frame"] = true,
	
	["Load predefined settings"] = true,
	["Common"] = true,
	["Aggro"] = true,
	["Healer"] = true,
	
	["Load focus profiles"] = true,
	["Load predefined profiles"] = true,
	
	["Disable colored debuff aura"] = true,
	["Disable background color change when unit has debuff"] = true,
	["Disable bottom buff name"] = true,
	["Short unit names"] = true,
	["Reduce unit name to three letters"] = true,
	["Show group number"] = true,
	["Add group number to unit name string"] = true,
	
	["_Focus frames"] = true,
	["Sort focus"] = true,
	["Dynamic sort lvl1 - health"] = true,
	["Dynamic sort lvl2 - range"] = true,
	["Dynamic sort lvl3 - class"] = true,
	["Dynamic sort lvl3 - anti overheal"] = true,
	["Aggro units on top"] = true,
	
	["Focus aura"] = true,
	
	["Frame size"] = true,
	["Size"] = true,
	["Size of the raid frames"] = true,
	["Scale"] = true,
	["Width"] = true,
	
	
	["Special aura - Target"] = true,
	["Change background color to blue of target unit"] = true,
	
	["Special aura - Enemy target"] = true,
	["Change background color to red of enemy target unit"] = true,
	
	["Exclude target unit from sorting"] = true,
	["Target on top"] = true,
	

	
	["Lock"] = true;
	["Show group titles"] = true,
	["Extra width"] = true,
	["Focus frame extra width"] = true,
	["Units limit number"] = true,
	["Units limit number"] = true,
	

	["Populate with range"] = true,
	["Automatically populate focus frame with units in range"] = true,
	
	["Set unit HP filter"] = true,
	["Unit filtering treshold"] = true,
	
	["Requires UI reload"] = true,
	
	["Lock"] = true,
	["Lock/Unlock the raid frames"] = true,
	["Unlocked"] = true,
	["Locked"] = true,

	["Hide party interface"] = true,
	["Hide party interface in raid - Blizzard's version may fail sometimes"] = true,

	["Health text"] = true,
	["Set health display type"] = true,
	["Current and max health"] = true,
	["Health deficit"] = true,
	["Health percentage"] = true,
	["Current health"] = true,
	["Hide health text"] = true,

	["Invert health bars"] = true,
	["Invert the growth of the health bars"] = true,

	["Buff filter"] = true,
	["Set buff filter"] = true,
	["Add buff"] = true,
	["Add a buff"] = true,
	["<name of buff>"] = true,
	
	["Debuff filter"] = true,
	["Set debuff filter"] = true,
	["Add debuff"] = true,
	["Add a debuff"] = true,
	["<name of debuff>"] = true,

	["Show group titles"] = true,
	["Toggle display of titles above each group frame"] = true,
	["Group subsort"] = true,
	["Select how you wish to sort the members of each group"] = true,
	["By name"] = true,
	["By class"] = true,
	["Grid like"] = true,
	["Blizzard default"] = true,
	["Group sort"] = true,
	["Group method"] = true,
	["Dead and offline units sub sort"] = true,
	["Dead or offline units are moved to the bottom of frame"] = true,
	["Reverse sort"] = true,
	
	["Select how you wish to show the groups"] = true,
	["By group"] = true,
	["By class"] = true,
	["By order"] = true,
	["Units per column"] = true,
	["Set max number of units in column - effect only if Grid like group sort is enabled"] = true,
	["Pyramid BottomRight"] = true,
	["Pyramid BottomLeft"] = true,
	["Pyramid TopRight"] = true,
	["Pyramid TopLeft"] = true,


	["Anchor"] = true,
	["Set the anchor of buffs/debuffs"] = true,
	["Set size of buff/debuff texture"] = true,
	["Buff/debuff texture size"] = true,	
	["Buff/Debuff visibility"] = true,
	["Show buffs or debuffs on the raid frames"] = true,
	["Only buffs"] = true,
	["Only debuffs"] = true,
	["Buffs and debuffs"] = true,
	["Nothing"] = true,
	["Power type visiblity"] = true,
	["Toggle the display of certain power types (Mana, Rage, Energy)"] = true,
	["Mana"] = true,
	["Toggle the display of mana bars"] = true,
	["Energy & Focus"] = true,
	["Toggle the display of energy and focus bars"] = true,
	["Rage"] = true,
	["Toggle the display of rage bars"] = true,
	["Show dispellable debuffs"] = true,
	["Toggle display of dispellable debuffs"] = true,
	

	["Show filtered buffs"] = true,
	["Toggle display of filtered buffs"] = true,
	
	["Show dispellable debuffs within range"] = true,
	["Toggle display debuffs within 28Y range"] = true,
	["Show filtered debuffs"] = true,
	["Toggle display of filtered debuffs"] = true,
	
	["Buff/debuff slot number"] = true,
	["Set max number of buffs and debuffs"] = true,

	["Set the growth of the buffs/debuffs"] = true,

	["Buffs/Debuffs"] = true,
	["_Buffs/Debuffs"] = true,
	["Bar textures"] = true,
	["Set the texture used on health and mana bars"] = true,

	["Scale"] = true,
	["Set the scale of the raid frames"] = true,
	["Layout"] = true,
	["Set the layout of the raid frames"] = true,
	["Reset layout"] = true,
	["Reset the position of sRaidFrames"] = true,
	["Predefined Layout"] = true,
	["Set a predefined layout for the raid frames"] = true,
	["Sticky"] = true,
	["CT_RaidAssist"] = true,
	["Horizontal"] = true,
	["Vertical"] = true,

	["Background color"] = true,
	["Change the background color"] = true,
	["Border color"] = true,
	["Change the border color"] = true,
	["Border"] = true,
	["Set about borders around the raid frames"] = true,
	["Toggle border"] = true,
	["Toggle the display of borders around the raid frames"] = true,
	["Border texture"] = true,
	["Select border texture"] = true,
	["Original"] = true,
	["Ace"] = true,
	["Santa"] = true,
	["ThickEdge"] = true,
	["Snow"] = true,
	["Grid"] = true,
	["Tooltip display"] = true,
	["Determine when a tooltip is displayed"] = true,
	["Never"] = true,
	["Only when not in combat"] = true,
	["Always"] = true,
	["Highlight units with aggro"] = true,
	["Turn the border of units who have aggro red"] = true,
	["_Range"] = true,
	["Set about range"] = true,
	["Show estimated range"] = true,
	["Show estimated range next to player's name"] = true,
	["Show estimated range only for focus units"] = true,
	["Enable light range check"] = true,
	["Enable 28y range check in Instances and 40y coordinates dependant range check in Outdoors and Bgs - Suggested when you neither play healing class nor using Blizzard frames, agUnitFrames or LunaUnitFrames"] = true,
	
	["Enable accurate range check"] = true,
	["Enable 40y range check that requires certain spells to be on actionbar and Blizzard frames, agUnitFrames or LunaUnitFrames to be present - Only healing classes can use accurate range check"] = true,
	
	["Enable combined range check"] = true,
	["Enable 40y accurate range check only in combat otherwise light range check is active"] = true,


	["_Arrows"] = true,
	["Coordinates dependant functionality, won't work in instances"] = true,
	["Enable arrows"] = true,
	["Enable unit arrows"] = true,
	["Focus units only"] = true,
	["Enable arrows only for focus units"] = true,


	["_Debug"] = true,
	["Set about debug"] = true,
	["Enable range calculation debug"] = true,
	["Range accuracy calculation, only for testing"] = true,
	["Enable incomming heal debug"] = true,
	["Incomming heal debug, only for testing. Prefixes: HCOM - HealComm, SRF - SRaidFrames, HBOT - HealBot, HAS - Healer Assist"] = true,
	["Enable incomming resurrection debug"] = true,
	["Incomming resurrection debug, only for testing. Prefixes: HCOM - HealComm, SRF - SRaidFrames, HBOT - HealBot, HAS - Healer Assist"] = true,
	
	
	["Alpha"] = true,
	["The alpha level for units who are out of range"] = true,
	
	["Range frequency"] = true,
	["The interval between which range checks are performed"] = true,
	
	["Accurate range frequency factor"] = true,
	["Increase or decrease time needed for full units scan - if you experience performance drop please increase the value"] = true,

	["Show Group/Class"] = true,
	["Toggle the display of certain Groups/Classes - Active if frames are locked"] = true,
	["Classes"] = true,
	["Warriors"] = true,
	["Toggle the display of Warriors"] = true,
	["Paladins"] = true,
	["Toggle the display of Paladins"] = true,
	["Shamans"] = true,
	["Toggle the display of Shamans"] = true,
	["Hunters"] = true,
	["Toggle the display of Hunters"] = true,
	["Warlocks"] = true,
	["Toggle the display of Warlocks"] = true,
	["Mages"] = true,
	["Toggle the display of Mages"] = true,
	["Druids"] = true,
	["Toggle the display of Druids"] = true,
	["Rogues"] = true,
	["Toggle the display of Rogues"] = true,
	["Priests"] = true,
	["Toggle the display of Priests"] = true,

	["Groups"] = true,
	["Group 1"] = true,
	["Toggle the display of Group 1"] = true,
	["Group 2"] = true,
	["Toggle the display of Group 2"] = true,
	["Group 3"] = true,
	["Toggle the display of Group 3"] = true,
	["Group 4"] = true,
	["Toggle the display of Group 4"] = true,
	["Group 5"] = true,
	["Toggle the display of Group 5"] = true,
	["Group 6"] = true,
	["Toggle the display of Group 6"] = true,
	["Group 7"] = true,
	["Toggle the display of Group 7"] = true,
	["Group 8"] = true,
	["Toggle the display of Group 8"] = true,

	["Growth"] = true,
	["Set the growth of the raid frames"] = true,
	["Up"] = true,
	["Down"] = true,
	["Left"] = true,
	["Right"] = true,
	["Combined"] = true,
	["TopRight"] = true,
	["BottomRight"] = true,


	["Border"] = true,
	["Toggle the display of borders around the raid frames"] = true,
	["Frame spacing"] = true,
	["Set the spacing between each of the raid frames"] = true,

	["Offline"] = true,
	["Ghost"] = true,
	["Dead"] = true,
	["Resurrected"] = true,
	["Can Recover"] = true,
	["Feign Death"] = true,
	["Unknown"] = true,

	["Warrior"] = true,
	["Mage"] = true,
	["Paladin"] = true,
	["Shaman"] = true,
	["Druid"] = true,
	["Hunter"] = true,
	["Rogue"] = true,
	["Warlock"] = true,
	["Priest"] = true,
	
	["Shield"] = true,
	["Carrier"] = true,
	["Rezzed"] = true,
	["Soulstoned"] = true,
	["Intervened"] = true,
	["Innervate"] = true,
	["Spirit"] = true,
	["Shield Wall"] = true,
	["Last stand"] = true,
	["Gifted"] = true,
	["Ice block"] = true,
	["Vanished"] = true,
	["Stealthed"] = true,
	["Infused"] = true,
	["Fear Ward"] = true,
	["Protection"] = true,
	["Divine Shield"] = true,

	["Right-click for options."] = true,
} end)
