local L = AceLibrary("AceLocale-2.2"):new("XLoot")

L:RegisterTranslations("zhCN", function() 
	return {
		catSnap = "框体吸附设置",
		catLoot = "物品拾取设置",
		catFrame = "框体设置",
		catInfo = "拾取信息",
		catGeneralAppearance = "一般表现",
		catFrameAppearance = "框体表现",
		catLootAppearance = "拾取物品表现",
		catExtras = "额外",
		
		["2.0 compatability"] = "wow2.0修复",
		["If you're getting errors with table.setn, enable this"] = "出现table.setn报错时,勾选此项",
			
		optLock = "锁定",
		optOptions = "设置界面",
		optBehavior = "行为设置",
		optCursor = "吸附鼠标",
		optSmartsnap = "快速吸附",
		optSnapoffset = "吸附后鼠标偏移坐标值",
		optCollapse = "Collapse loot buttons",
		optDragborder = "可移动边框",
		optLootexpand = "Fit frame width to loot names",
		optAltoptions = "当Alt+RightClick显示菜单",
		optSwiftloot = "当Shift-拾取时不显示",
		optQualitytext = "显示物品品质",
		optInfotext = "显示物品信息",
		optLinkAll = "显示所有的链接按钮",
		optLinkAllVis = "可见: ",
		optLinkAllThreshold = "链接高于定义等级的物品",
		optLinkAllChannels = "总是链接到...",
		optAppearance = "外观",
		optQualityborder = "边框着色",
		optQualityframe = "背景着色",
		optLootqualityborder = "内边框着色",
		optBgcolor = "整体背景着色",
		optBordercolor = "整体边框着色",
		optTexColor = "物品图标着色",
		optHighlightLoot = "高亮拾取",
		optHighlightThreshold = "高亮条件设置", 
		optLootbgcolor = "拾取框背景着色",
		optLootbordercolor = "拾取框边框着色",
		optInfoColor = "信息文本颜色",
		optScale = "缩放",
		optAdvanced = "高级选项",
		optDebug = "Debug Messages",
		optDefaults = "恢复默认",
		
		descLock = "Makes loot frame unmoveable",
		descOptions = "Show the options dropdown",
		descBehavior = "Change how XLoot behaves",
		descCursor = "Snap the loot frame to the cursor whenever you loot something",
		descSmartsnap = "Snaps the loot frame only vertically to the cursor when the list shifts as you loot a item so it doesn't jump around",
		descSnapoffset = "Sets a distance from the middle of the first loot icon to snap to, horizontally",
		descCollapse = "Collapse looted (empty) buttons and place cursor over next frame if the Cursor option is enabled.",
		descDragborder = "Allows the loot window to be moved by dragging the frame's border, instead of just the buttons, which can otherwise be clicked through",
		descLootexpand = "Changes frame width to match loot names. Short names mean thin frames, long names make the frames widen",
		descAltoptions = "Allows you to Alt+RightClick on loot to bring up the XLoot menu. Can be disabled to not mess with other mods.",
		descSwiftloot = "Attempts to find out when loot is being shift-rightclick-looted, and never shows the frame if there is space for all items. Should reduce lag when shift-looting, disable if you run into problems.",
		descQualitytext = "Show a additional line above the item name with the item's Quality",
		descInfotext = "Show a addition line below the item name with the item's Information",
		descLinkAll = "The Link All button, a button that pops up a menu with all available channels, letting you send the current open loot to any of them.",
		descLinkAllVis = "When the Link All button should be visible",
		descLinkAllThreshold = "Only link items higher than the threshold.",
		descLinkAllChannels = "Always link to these channels when left-clicking Link All. |cFFFF0000If none are checked, left-clicking Link All will show the Link All menu.|r",
		descAppearance = "Coloring, scaling, and skin of XLootFrame and each individual loot button",
		descQualityborder = "Colors lootframe border by the highest quality item",
		descQualityframe = "Colors lootframe background by the highest quality item",
		descLootqualityborder = "Colors loot borders by quality",
		descHighlightLoot = "Highlights each loot frame by quality",
		descHighlightThreshold = "The minimum quality at which loot frames will be highlighted",
		descBgcolor = "Change the background color for the loot frame itself",
		descBordercolor = "Change the border color of the frame itself",
		descTexColor = "Color the border of the actual item icon/texture by quality",
		descLootbgcolor = "Change the background color for every loot item",
		descLootbordercolor = "Change the border color of every loot item",
		descInfoColor = "Change the color of the information text",
		descScale = "Scale of the loot frame",
		descAdvanced = "Options you may not want to mess with, but can anyway.",
		descDebug = "Show debug messages",
		descDefaults = "Reinstate the database that comes with XLoot and set all the options back to their defaults",
		
		qualityQuest = "任务物品",
		
		guiTitle = "XLoot设置",
		
		itemWeapon = "武器",
		
		evHerbs = "草药采集",
		evOpenNT = "打开 - No Text",
		evOpen = "打开",
		
		linkallloot = "链接...",
		linkallchanneldesc = "Automatically link loot to %s when left-clicking Link All",
		}
end)