-- Item Info Key
PACKUP_INFO_ID = "ID"
PACKUP_INFO_NAME = "Name"
PACKUP_INFO_LINK = "Link"
PACKUP_INFO_RARITY = "Rarity"
PACKUP_INFO_TYPE = "Type"
PACKUP_INFO_SUBTYPE = "SubType"
PACKUP_INFO_MINILEVEL = "MiniLevel"
PACKUP_INFO_STACK = "StackCount"
PACKUP_INFO_EQUIPLOC = "EquipLocation"
PACKUP_INFO_TEXTURE = "Texture"
PACKUP_INFO_QUANTITY = "Quantity"
PACKUP_INFO_UNKONW = "[Unknow]"

-- Color
PACKUP_COLOR_PREFIX = "|c"
PACKUP_COLOR_SUFFIX = "|r"

-- Pattern
PACKUP_ITEMLINK = "|H(item:%d+:%d+:%d+:%d+)|h%[([^]]+)%]|h|r$"

-- Order
PACKUP_ORDER_ASC = 0
PACKUP_ORDER_DESC = 1
