-- Addon Info
PACKUP_NAME = "|c0000FFFF物品整理|r"
PACKUP_VERSION = "0.7.0"
PACKUP_PUBTYPE = "|c00FFFF00Alpha|r"

-- Bags
PACKUP_BAG_NORMAL = "容器"
PACKUP_BAG_QUIVER = "箭袋"
PACKUP_BAG_AMMO = "弹药袋"
PACKUP_BAG_SOUL = "灵魂袋"
PACKUP_BAG_HERB = "草药袋"
PACKUP_BAG_ENCHANT = "附魔材料袋"
-- TBC Bags
PACKUP_BAG_MINE = "矿石袋"
PACKUP_BAG_GEM = "珠宝袋"
PACKUP_BAG_ENGINEER = "工程袋"

-- Message String
PACKUP_ERR_PREFIX = PACKUP_NAME.."：错误 - "
PACKUP_ERR_NOMSG = PACKUP_ERR_PREFIX.."文字信息为空"
PACKUP_ERR_BANKCLOSE = PACKUP_ERR_PREFIX.."银行未打开"
PACKUP_ERR_OUTOFBOUND = PACKUP_ERR_PREFIX.."数组越界"

PACKUP_MSG_ONLOAD = PACKUP_NAME.." "..PACKUP_VERSION.." "..PACKUP_PUBTYPE.." 载入完成"
PACKUP_MSG_BAG_PACKUP = PACKUP_NAME.."：正在整理 |c0000FF00%s|r";
PACKUP_MSG_BAG_DISORDER = PACKUP_NAME.."：正在打乱 |c0000FF00%s|r";
PACKUP_MSG_BAG_COMPRESS = PACKUP_NAME.."：正在压缩 |c0000FF00"..PACKUP_BAG_NORMAL.."|r";
PACKUP_MSG_COMPLETE = PACKUP_NAME.."：|c00FFFF00所有背包整理完成|r"
PACKUP_MSG_NOTSUPPORT_LOADVAR = PACKUP_NAME.."：|c00FFFF00变量配置功能尚未支持|r"
PACKUP_MSG_PACKUP_ALLPERCENT = PACKUP_NAME.."：已完成 |c00FFFF00%2d%%|r";
PACKUP_MSG_PACKUP_BAGPERCENT = "|c0000FF00%s|r 已完成 |c00FFFF00%d / %d|r";
PACKUP_MSG_PACKUP_ZIPTITLE = PACKUP_NAME.."：|c00FFFF00正在压缩物品|r";
