  CT_RaidTracker_Zones = {
		"熔火之心",
		"黑翼之巢",
		"祖尔格拉布",
		"奥妮克希亚的巢穴",
		"安其拉神殿",
		"安其拉废墟",
		"纳克萨玛斯"
	};

	CT_RaidTracker_Bosses = {
		["熔火之心"] = {
			"鲁西弗隆",
			"玛格曼达",
			"基赫纳斯",
			"加尔",
			"沙斯拉尔",
			"迦顿男爵",
			"焚化者古雷曼格",
			"萨弗隆先驱者",
			"管理者埃克索图斯",
			"拉格纳罗斯",
		},
		["黑翼之巢"] = {
			"狂野的拉佐格尔",
			"堕落的瓦拉斯塔兹",
			"勒什雷尔",
			"费尔默",
			"埃博诺克",
			"弗莱格尔",
			"克洛玛古斯",
			"奈法利安",
		},
		["祖尔格拉布"] = {
			"高阶祭司耶克里克",
			"高阶祭司温诺希斯",
			"高阶祭司玛尔罗",
			"高阶祭司塞卡尔",
			"高阶祭司娅尔罗",
			"哈卡",
			"血领主曼多基尔",
			"哈扎拉尔",
			"加兹兰卡",
			"乌苏雷",
			"妖术师金度",
			"格里雷克",
			"雷纳塔基",
		},
		["安其拉废墟"] = {
			"库林纳克斯",
			"拉贾克斯将军",
			"吞咽者布鲁",
			"狩猎者阿亚米斯",
			"莫阿姆",
			"无疤者奥斯里安",
		},
		["安其拉"] = {
			"预言者斯克拉姆",
			"克里勋爵",
			"亚尔基公主",
			"维姆",
			"沙尔图拉",
			"顽强的范克瑞斯",
			"哈霍兰公主",
			"维希度斯",
			"维克尼拉斯大帝",
			"维克洛尔大帝",
			"奥罗",
			"克苏恩",
		},
	 ["纳克萨玛斯"] = {
		"帕奇维克",
		"格罗布鲁斯",
		"格拉斯",
		"塔迪乌斯",
		"教官拉苏维奥斯",
		"收割者哥司克",
		"大领主莫格莱尼",
		"库尔塔兹领主",
		"女公爵布劳缪克丝",
		"瑟里耶克爵士",
		"瘟疫使者诺斯",
		"肮脏的希尔盖",
		"洛欧塞布",
		"阿努布雷坎",
		"黑女巫法琳娜",
		"迈克斯纳",
		"萨菲隆",
		"克尔苏加德",
	},
		["奥妮克希亚"] = 1,
		["卡扎克"] = 1,
		["艾索雷葛斯"] = 1,
		["翡翠龙王"] = {
			"莱索恩",
			"泰拉尔",
			"艾莫莉丝",
			"伊森德雷",
		},
		["小怪掉落"] = 1,
	};

	CT_RaidTracker_lang_LeftGroup = "([^%s]+)离开了团队";
	CT_RaidTracker_lang_JoinedGroup = "([^%s]+)加入了团队";
  CT_RaidTracker_lang_ReceivesLoot1 = "([^%s]+)获得了物品：(|c%x+|Hitem:%d+:%d+:%d+:%d+|h%[.-%]|h|r)。";
  CT_RaidTracker_lang_ReceivesLoot2 = "你获得了物品：(|c%x+|Hitem:%d+:%d+:%d+:%d+|h%[.-%]|h|r)。";   
  CT_RaidTracker_lang_ReceivesLoot3 = "([^%s]+)获得了物品：(|c%x+|Hitem:%d+:%d+:%d+:%d+|h%[.-%]|h|r)x(%d+)。"; 
  CT_RaidTracker_lang_ReceivesLoot4 = "你得到了物品：(|c%x+|Hitem:%d+:%d+:%d+:%d+|h%[.-%]|h|r)x(%d+)。";  
  CT_RaidTracker_lang_ReceivesLootYou = "你";
  CT_RaidTracker_lang_UnknownEntity = "未知目标";

CT_RaidTracker_ZoneTriggers = {
	["熔火之心"] = "熔火之心",
	["黑翼之巢"] = "黑翼之巢",
	["祖尔格拉布"] = "祖尔格拉布",
	["奥妮克希亚的巢穴"] = "奥妮克希亚的巢穴",
	["安其拉"] = "安其拉神殿",
	["安其拉废墟"] = "安其拉废墟",
	["纳克萨玛斯"] = "纳克萨玛斯",
};

CT_RaidTracker_BossUnitTriggers = {
	["鲁西弗隆"] = "鲁西弗隆",
	["玛格曼达"] = "玛格曼达",
	["基赫纳斯"] = "基赫纳斯",
	["加尔"] = "加尔",
	["沙斯拉尔"] = "沙斯拉尔",
	["迦顿男爵"] = "迦顿男爵",
	["焚化者古雷曼格"] = "焚化者古雷曼格",
	["萨弗隆先驱者"] = "萨弗隆先驱者",
	["管理者埃克索图斯"] = "管理者埃克索图斯",
	["拉格纳罗斯"] = "拉格纳罗斯",
	["烈焰行者护卫"] = "IGNORE",
	["烈焰行者"] = "IGNORE",
	["熔核摧毁者"] = "IGNORE",
	["熔核巨人"] = "IGNORE",
	["火焰之王"] = "IGNORE",
	["熔岩奔腾者"] = "IGNORE",
	["熔岩元素"] = "IGNORE",
	["烈焰守卫"] = "IGNORE",
	["上古熔火恶犬"] = "IGNORE",
	["熔火怒犬"] = "IGNORE",
	["火焰驱逐者"] = "IGNORE",
	["熔火恶犬"] = "IGNORE",
	["烈焰行者医师"] = "IGNORE",
	["烈焰行者精英"] = "IGNORE",
	["火焰之子"] = "IGNORE",
	
	["狂野的拉佐格尔"] = "狂野的拉佐格尔",
	["堕落的瓦拉斯塔兹"] = "堕落的瓦拉斯塔兹",
	["勒什雷尔"] = "勒什雷尔",
	["费尔默"] = "费尔默",
	["埃博诺克"] = "埃博诺克",
	["弗莱格尔"] = "弗莱格尔",
	["克洛玛古斯"] = "克洛玛古斯",
	["奈法利安"] = "奈法利安",
	["维克多·奈法里奥斯"] = "奈法利安",
	["Grethok the Controller"] = "IGNORE",
	["Blackwing Guardsman"] = "IGNORE",
	["Blackwing Legionnaire"] = "IGNORE",
	["Blackwing Mage"] = "IGNORE",
	["Death Talon Dragonspawn"] = "IGNORE",
	["Black Drakonid"] = "IGNORE",
	["Blue Drakonid"] = "IGNORE",
	["Bronze Drakonid"] = "IGNORE",
	["Green Drakonid"] = "IGNORE",
	["Red Drakonid"] = "IGNORE",
	["Chromatic Drakonid"] = "IGNORE",
	["Bone Construct"] = "IGNORE",
	["Corrupted Infernal"] = "IGNORE",
	["Corrupted Blue Whelp"] = "IGNORE",
	["Corrupted Red Whelp"] = "IGNORE",
	["Corrupted Green Whelp"] = "IGNORE",
	["Corrupted Bronze Whelp"] = "IGNORE",
	["Death Talon Hatcher"] = "IGNORE",
	["Blackwing Taskmaster"] = "IGNORE",
	
	["高阶祭司耶克里克"] = "高阶祭司耶克里克",
	["高阶祭司温诺希斯"] =	"高阶祭司温诺希斯",
	["高阶祭司玛尔罗"] =	"高阶祭司玛尔罗",
	["高阶祭司塞卡尔"] = "高阶祭司塞卡尔",
	["高阶祭司娅尔罗"] =	"高阶祭司娅尔罗",
	["哈卡"] = "哈卡",
	["血领主曼多基尔"] = "血领主曼多基尔",
	["哈扎拉尔"] = "哈扎拉尔",
	["加兹兰卡"] = "加兹兰卡",
	["乌苏雷"] = "乌苏雷",
	["妖术师金度"] = "妖术师金度",
	["格里雷克"] = "格里雷克",
	["雷纳塔基"] = "雷纳塔基",
	["Zulian Prowler"] = "IGNORE",
	["Zulian Guardian"] = "IGNORE",
	["Parasitic Serpent"] = "IGNORE",
	["Spawn of Mar'li"] = "IGNORE",
	["Ohgan"] = "IGNORE",
	["Frenzied Bloodseeker Bat"] = "IGNORE",
	
	["奥妮克希亚"] = "奥妮克希亚",
	["卡扎克"] = "卡扎克",
	["艾索雷葛斯"] = "艾索雷葛斯",
	["莱索恩"] = "莱索恩",
	["泰拉尔"] = "泰拉尔",
	["艾莫莉丝"] = "艾莫莉丝",
	["伊森德雷"] = "伊森德雷",
	
	["Onyxian Whelp"] = "IGNORE",
	["奥妮克希亚守卫"] = "IGNORE",
	["泰拉尔的阴影"] = "IGNORE",
	["Spirit Shade"] = "IGNORE",
	["疯狂的德鲁伊之魂"] = "IGNORE",
	
	["库林纳克斯"] = "库林纳克斯",
	["拉贾克斯将军"] = "拉贾克斯将军",
	["吞咽者布鲁"] = "吞咽者布鲁",
	["狩猎者阿亚米斯"] = "狩猎者阿亚米斯",
	["莫阿姆"] = "莫阿姆",
	["无疤者奥斯里安"] = "无疤者奥斯里安",
	["布鲁的卵"] = "IGNORE",
	["Canal Frenzy"] = "IGNORE",
	["Mana Fiend"] = "IGNORE",
	["Silicate Feeder"] = "IGNORE",
	["Hive'Zara Hatchling"] = "IGNORE",
	["Hive'Zara Larva"] = "IGNORE",
	["Vekniss Hatchling"] = "IGNORE",
	["Anubisath Warrior"] = "IGNORE",
	
	["预言者斯克拉姆"] = "预言者斯克拉姆",
	["克里勋爵"] = "克里勋爵",
	["亚尔基公主"] = "亚尔基公主",
	["维姆"] = "维姆",
	["沙尔图拉"] = "沙尔图拉",
	["顽强的范克瑞斯"] = "顽强的范克瑞斯",
	["哈霍兰公主"] = "哈霍兰公主",
	["维希度斯"] = "维希度斯",
	["维克尼拉斯大帝"] = "维克尼拉斯大帝",
	["维克洛尔大帝"] = "维克洛尔大帝",
	["奥罗"] = "奥罗",
	["克苏恩"] = "克苏恩",
	["Ouro Scarab"] = "IGNORE",
	["Spawn of Fankriss"] = "IGNORE",
	["Qiraji Scorpion"] = "IGNORE",
	["Qiraji Scarab"] = "IGNORE",
	["Vile Scarab"] = "IGNORE",
	["Yauj Brood"] = "IGNORE",
	["Sartura's Royal Guard"] = "IGNORE",
	["Sartura's Royal Guard"] = "IGNORE",
	["Poison Cloud"] = "IGNORE",
	["Vekniss Drone"] = "IGNORE",
	["Glob of Viscidus"] = "IGNORE",
	
	["帕奇维克"] = "帕奇维克",
	["格罗布鲁斯"] = "格罗布鲁斯",
	["格拉斯"] = "格拉斯",
	["塔迪乌斯"] = "塔迪乌斯",
	["教官拉苏维奥斯"] = "教官拉苏维奥斯",
	["收割者哥司克"] = "收割者哥司克",
	["大领主莫格莱尼"] = "大领主莫格莱尼",
	["库尔塔兹领主"] = "库尔塔兹领主",
	["女公爵布劳缪克丝"] = "女公爵布劳缪克丝",
	["瑟里耶克爵士"] = "瑟里耶克爵士",
	["瘟疫使者诺斯"] = "瘟疫使者诺斯",
	["肮脏的希尔盖"] = "肮脏的希尔盖",
	["洛欧塞布"] = "洛欧塞布",
	["阿努布雷坎"] = "阿努布雷坎",
	["黑女巫法琳娜"] = "黑女巫法琳娜",
	["迈克斯纳"] = "迈克斯纳",
	["萨菲隆"] = "萨菲隆",
	["克尔苏加德"] = "克尔苏加德",
	["Grobbulus Cloud"] = "IGNORE",
	
	["Spotlight"] = "IGNORE",
	["Roach"] = "IGNORE",
	["Snake"] = "IGNORE",
	["Brown Snake"] = "IGNORE",
	["Crimson Snake"] = "IGNORE",
	["Black Kingsnake"] = "IGNORE",
	["Beetle"] = "IGNORE",
	["Dupe Bug"] = "IGNORE",
	["Fire Beetle"] = "IGNORE",
	["Scorpion"] = "IGNORE",
	["Frog"] = "IGNORE",
	["Hooktooth Frenzy"] = "IGNORE",
	["Sacrificed Troll"] = "IGNORE",
	["Spider"] = "IGNORE",
	["Rat"] = "IGNORE",
	["Jungle Toad"] = "IGNORE",
	["Field Repair Bot 74A"] = "IGNORE",
	
	["DEFAULTBOSS"] = "小怪掉落",
};

	CT_RaidTracker_lang_BossKills_Majordomo_Yell = "不……不可能！等一下……我投降！我投降！";
	CT_RaidTracker_lang_BossKills_Majordomo_BossName = "管理者埃克索图斯";
  CT_RaidTracker_lang_BossKills_Ignore_Razorgore_Yell = "我自由了！ 那个东西再也不能折磨我了！";
  
  PlayerGroupsIndexes = {"战士","牧师","法师","盗贼","圣骑士","德鲁伊","术士","萨满祭司","猎人"};
  CT_RaidTracker_lang_Class_Colors = {
              ["猎人"] = { r = 0.67, g = 0.83, b = 0.45 },
              ["术士"] = { r = 0.58, g = 0.51, b = 0.79 },
              ["牧师"] = { r = 1.0, g = 1.0, b = 1.0 },
              ["圣骑士"] = { r = 0.96, g = 0.55, b = 0.73 },
              ["法师"] = { r = 0.41, g = 0.8, b = 0.94 },
              ["盗贼"] = { r = 1.0, g = 0.96, b = 0.41 },
              ["德鲁伊"] = { r = 1.0, g = 0.49, b = 0.04 },
              ["萨满祭司"] = { r = 0.96, g = 0.55, b = 0.73 },
              ["战士"] = { r = 0.78, g = 0.61, b = 0.43 }
	}
