--To add a new font or texture, simply put them in the same folder as the others and add it to the appropriate list below.
--Do note that the file paths are case sensitive.

PunschrulleFonts = {
	Aldrich = "Fonts\\ARIALN.TTF",
	Bangers = "Fonts\\ARIALN.TTF",
	Bazooka = "Fonts\\ARIALN.TTF",
	Celestia = "Fonts\\ARIALN.TTF",
	DorisPP = "Fonts\\ARIALN.TTF",
	Enigmatic = "Fonts\\ARIALN.TTF",
	FasterOne = "Fonts\\ARIALN.TTF",
	Fitzgerald = "Fonts\\ARIALN.TTF",
	Gentium = "Fonts\\ARIALN.TTF",
	Iceland = "Fonts\\ARIALN.TTF",
	Inconsolata = "Fonts\\ARIALN.TTF",
	LiberationSans = "Fonts\\ARIALN.TTF",
	Luna = "Fonts\\ARIALN.TTF",
	MetalLord = "Fonts\\ARIALN.TTF",
	Optimus = "Fonts\\ARIALN.TTF",
	SansNarrow = "Fonts\\ARIALN.TTF",
	TradeWinds = "Fonts\\ARIALN.TTF",
	VeraSerif = "Fonts\\ARIALN.TTF",
	Vixar = "Fonts\\ARIALN.TTF",
	Yellowjacket = "Fonts\\ARIALN.TTF",
	Exocet = "Fonts\\ARIALN.TTF",
	Budhand = "Fonts\\ARIALN.TTF",
	ArialNarrow = "Fonts\\ARIALN.TTF",
	Skurri = "Fonts\\ARIALN.TTF",
	Morpheus = "Fonts\\ARIALN.TTF",
}

PunschrulleTextures = {
	Aluminium = "Interface\\AddOns\\Punschrulle\\media\\textures\\Aluminium",
	Armory = "Interface\\AddOns\\Punschrulle\\media\\textures\\Armory",
	BantoBar = "Interface\\AddOns\\Punschrulle\\media\\textures\\BantoBar",
	Bars = "Interface\\AddOns\\Punschrulle\\media\\textures\\Bars",
	Blizzard = "Interface\\TargetingFrame\\UI-StatusBar",
	Dabs = "Interface\\AddOns\\Punschrulle\\media\\textures\\Dabs",
	Diagonal = "Interface\\AddOns\\Punschrulle\\media\\textures\\Diagonal",
	Frost = "Interface\\AddOns\\Punschrulle\\media\\textures\\Frost",
	Glamour = "Interface\\AddOns\\Punschrulle\\media\\textures\\Glamour",
	Glamour2 = "Interface\\AddOns\\Punschrulle\\media\\textures\\Glamour2",
	Glamour3 = "Interface\\AddOns\\Punschrulle\\media\\textures\\Glamour3",
	Glamour4 = "Interface\\AddOns\\Punschrulle\\media\\textures\\Glamour4",
	Glamour5 = "Interface\\AddOns\\Punschrulle\\media\\textures\\Glamour5",
	Glamour6 = "Interface\\AddOns\\Punschrulle\\media\\textures\\Glamour6",
	Glamour7 = "Interface\\AddOns\\Punschrulle\\media\\textures\\Glamour7",
	Glaze = "Interface\\AddOns\\Punschrulle\\media\\textures\\Glaze",
	Gloss = "Interface\\AddOns\\Punschrulle\\media\\textures\\Gloss",
	Graphite = "Interface\\AddOns\\Punschrulle\\media\\textures\\Graphite",
	Healbot = "Interface\\AddOns\\Punschrulle\\media\\textures\\Healbot",
	LiteStep = "Interface\\AddOns\\Punschrulle\\media\\textures\\LiteStep",
	Lyfe = "Interface\\AddOns\\Punschrulle\\media\\textures\\Lyfe",
	Minimalist = "Interface\\AddOns\\Punschrulle\\media\\textures\\Minimalist",
	Otravi = "Interface\\AddOns\\Punschrulle\\media\\textures\\Otravi",
	Perl2 = "Interface\\AddOns\\Punschrulle\\media\\textures\\Perl2",
	Rocks = "Interface\\AddOns\\Punschrulle\\media\\textures\\Rocks",
	Ruben = "Interface\\AddOns\\Punschrulle\\media\\textures\\Ruben",
	Runes = "Interface\\AddOns\\Punschrulle\\media\\textures\\Runes",
	Skewed = "Interface\\AddOns\\Punschrulle\\media\\textures\\Skewed",
	Smooth = "Interface\\AddOns\\Punschrulle\\media\\textures\\Smooth",
	Striped = "Interface\\AddOns\\Punschrulle\\media\\textures\\Striped",
	Wisps = "Interface\\AddOns\\Punschrulle\\media\\textures\\Wisps",
	Xeon = "Interface\\AddOns\\Punschrulle\\media\\textures\\Xeon"
}