local AceLocale = AceLibrary("AceLocale-2.1")

AceLocale:RegisterTranslation("RaidOrganizerOptions", "deDE", function()
    return {
		["AA"] = "GG"
	}
end)

AceLocale:RegisterTranslation("RaidOrganizer", "deDE", function()
    return {
        ["CLOSE"] = "Schlie\195\159en",
        ["RESET"] = "Zur\195\188cksetzen",
		["RESETTAB"] = "Reset Tab",
		["ALLREMAIN"] = "All Remain",
        ["RAID"] = "Schlachtzug",
        ["CHANNEL"] = "Channel",
        ["DISPEL"] = "Dispellen",
        ["MT"] = "MT",
        ["HEAL"] = "heilen",
        ["DECURSE"] = "decursen",
        ["REMAINS"] = "Rest",
        ["ARRANGEMENT"] = "Einteilung",
        ["BROADCAST"] = "Broadcast",
        ["OPTIONS"] = "Optionen",
        ["STATS"] = "Statistik",
        ["PALADIN"] = "Paladin",
        ["DRUID"] = "Druide",
        ["PRIEST"] = "Priester",
        ["SHAMAN"] = "Schamane",
		["ROGUE"] = "Rogue",
		["WARRIOR"] = "Warrior",
		["MAGE"] = "Mage",
		["HUNTER"] = "Hunter",
		["WARLOCK"] = "Warlock",
		["Group1"] = "Group 1",
		["Group2"] = "Group 2",
		["Group3"] = "Group 3",
		["Group4"] = "Group 4",
		["Group5"] = "Group 5",
		["Group6"] = "Group 6",
		["Group7"] = "Group 7",
		["Group8"] = "Group 8",
        ["PALADINS"] = "Paladine",
        ["DRUIDS"] = "Druiden",
        ["PRIESTS"] = "Priester",
        ["SHAMANS"] = "Schamanen",
		["ROGUES"] = "Rogues",
		["WARRIORS"] = "Warriors",
		["MAGES"] = "Mages",
		["WARLOCKS"] = "Warlock",
		["HUNTERS"] = "Hunters",
        ["HEALARRANGEMENT1"] = "Healing arrangement",
		["HEALARRANGEMENT2"] = "Tank arrangement",
		["HEALARRANGEMENT3"] = "Kick arrangement",
		["HEALARRANGEMENT4"] = "Crowd Control arrangement",
		["HEALARRANGEMENT5"] = "Curse arrangement",
		["HEALARRANGEMENT6"] = "Intel Buff arrangement",
		["HEALARRANGEMENT7"] = "Stam Buff arrangement",
		["HEALARRANGEMENT8"] = "MOTW arrangement",
        ["FFA"] = "ffa", -- was der rest machen darf
        ["NO_CHANNEL"] = "Sie m\195\188ssen den Channel %q beitreten, bevor sie die Heilereinteilung bekannt geben k\195\182nnen",
        ["NOT_IN_RAID"] = "Sie sind in keinem Schlachtzug",
        ["FREE"] = "frei",
		["MULTIPLE_ARRANGEMENT"] = "Multiple arrangement",
        ["EDIT_LABEL"] = "Neue Bezeichnung f\195\188r die Gruppe %u",
        ["SHOW_DIALOG"] = "Zeige/Schliesse das Dialog",
        ["LABELS"] = "Beschriftungen",
        ["SAVEAS"] = "Speichern als",
        ["SET_SAVEAS"] = "Geben sie ein Namen f\195\188r den Set ein",
        ["SET_DEFAULT"] = "Standard",
        ["SET_CANNOT_DELETE_DEFAULT"] = "Sie k\195\182nnen den Standard-Set nicht l\195\182schen",
        ["SET_CANNOT_SAVE_DEFAULT"] = "Sie k\195\182nnen den Standard-Set nicht \195\188berschreiben",
        ["SET_ALREADY_EXISTS"] = "Der Set %q existiert bereits",
        ["SET_TO_MANY_SETS"] = "Sie k\195\182nnen nicht mehr als 32 Sets haben",
        ["AUTOSORT_DESC"] = "Automatische Sortierung f\195\188r die Gruppen",
        ["REPLY_NO_ARRANGEMENT"] = "Du bist f\195\188 nichts eingeteilt worden",
        ["REPLY_ARRANGEMENT_FOR"] = "Du bist f\195\188r eingeteilt",
        ["AUTOFILL"] = "Autofill",
        ["MSG_HEAL_FOR_ARRANGEMENT"] = "Fl\195\188stert 'assign' f\195\188r deine Heilereinteilung.",
        ["WHISPER"] = "Einteilungen fl\195\188stern",
        ["ARRANGEMENT_FOR"] = "Du bist f\195\188r folgendes eingeteilt:",
    }
end)
