-- By mymycracra (http://www.curse-gaming.com/en/profile-14788.html)
local AceLocale = AceLibrary("AceLocale-2.1")

AceLocale:RegisterTranslation("RaidOrganizerOptions", "frFR", function()
    return {
		["AA"] = "GG"
	}
end)

AceLocale:RegisterTranslation("RaidOrganizer", "frFR", function()
    return {
        ["CLOSE"] = "Ferme",
        ["RESET"] = "Reset All",
		["RESETTAB"] = "Reset Tab",
		["ALLREMAIN"] = "All Remain",
        ["RAID"] = "Raid",
        ["CHANNEL"] = "Canal",
        ["DISPEL"] = "Dispel",
        ["MT"] = "MT",
        ["HEAL"] = "Soin",
        ["DECURSE"] = "Decurse",
        ["REMAINS"] = "Restant",
        ["ARRANGEMENT"] = "Arrangement",
        ["BROADCAST"] = "Broadcast",
        ["OPTIONS"] = "Options",
        ["STATS"] = "Statistiques",
        ["PALADIN"] = "Paladin",
        ["DRUID"] = "Druide",
        ["PRIEST"] = "Priester",
        ["SHAMAN"] = "Schamane",
		["ROGUE"] = "Rogue",
		["WARRIOR"] = "Guerrier",
		["MAGE"] = "Mage",
		["WARLOCK"] = "Demoniste",
		["HUNTER"] = "Chasseur",
		["Group1"] = "Groupe 1",
		["Group2"] = "Groupe 2",
		["Group3"] = "Groupe 3",
		["Group4"] = "Groupe 4",
		["Group5"] = "Groupe 5",
		["Group6"] = "Groupe 6",
		["Group7"] = "Groupe 7",
		["Group8"] = "Groupe 8",
        ["PALADINS"] = "Paladin",
        ["DRUIDS"] = "Druides",
        ["PRIESTS"] = "Pr\195\170tres",
        ["SHAMANS"] = "Chamans",
		["ROGUES"] = "Rogues",
		["WARRIORS"] = "Guerriers",
		["MAGES"] = "Mages",
		["WARLOCKS"] = "Demonistes",
		["HUNTERS"] = "Chasseurs",
        ["HEALARRANGEMENT1"] = "Healing arrangement",
		["HEALARRANGEMENT2"] = "Tank arrangement",
		["HEALARRANGEMENT3"] = "Kick arrangement",
		["HEALARRANGEMENT4"] = "Crowd Control arrangement",
		["HEALARRANGEMENT5"] = "Curse arrangement",
		["HEALARRANGEMENT6"] = "Intel Buff arrangement",
		["HEALARRANGEMENT7"] = "Stam Buff arrangement",
		["HEALARRANGEMENT8"] = "MOTW arrangement",
        ["FFA"] = "ffa", -- was der rest machen darf
        ["NO_CHANNEL"] = "Vous devez vous connecter sur le canal %q avant d'organiser les soins",
        ["NOT_IN_RAID"] = "Vous n'etes pas en raid",
        ["FREE"] = "libre",
		["MULTIPLE_ARRANGEMENT"] = "Attribution multiple",
        ["EDIT_LABEL"] = "New label for group %u",
        ["SHOW_DIALOG"] = "Show/Hide the dialog",
        ["LABELS"] = "Labels",
        ["SAVEAS"] = "Save as",
        ["SET_SAVEAS"] = "Enter a name for the new set",
        ["SET_DEFAULT"] = "Default",
        ["SET_CANNOT_DELETE_DEFAULT"] = "You cannot delete the default set",
        ["SET_CANNOT_SAVE_DEFAULT"] = "You cannot overwrite the default set",
        ["SET_ALREADY_EXISTS"] = "The Set %q already exists",
        ["SET_TO_MANY_SETS"] = "You cannot have more than 32 sets",
        ["AUTOSORT_DESC"] = "Autosort for groups",
        ["REPLY_NO_ARRANGEMENT"] = "You are not assigned ",
        ["REPLY_ARRANGEMENT_FOR"] = "You are assigned to",
        ["AUTOFILL"] = "Autofill",
        ["MSG_HEAL_FOR_ARRANGEMENT"] = "Whisper 'assign' for your assignment.",
        ["WHISPER"] = "Whisper",
        ["ARRANGEMENT_FOR"] = "Your arrangement:",
    }
end)
